/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierDashboardRouteImport } from './routes/supplier/dashboard'
import { Route as RegisterSupplierRouteImport } from './routes/register/supplier'
import { Route as RegisterBuyerRouteImport } from './routes/register/buyer'
import { Route as BuyerDashboardRouteImport } from './routes/buyer/dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AccountSuspendedRouteImport } from './routes/account/suspended'
import { Route as AccountRejectedRouteImport } from './routes/account/rejected'
import { Route as AccountPendingRouteImport } from './routes/account/pending'
import { Route as SupplierTendersIndexRouteImport } from './routes/supplier/tenders/index'
import { Route as SupplierProposalsIndexRouteImport } from './routes/supplier/proposals/index'
import { Route as BuyerTendersIndexRouteImport } from './routes/buyer/tenders/index'
import { Route as AdminTendersIndexRouteImport } from './routes/admin/tenders/index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminAccountsIndexRouteImport } from './routes/admin/accounts/index'
import { Route as SupplierTendersIdRouteImport } from './routes/supplier/tenders/$id'
import { Route as SupplierProposalsIdRouteImport } from './routes/supplier/proposals/$id'
import { Route as BuyerTendersCreateRouteImport } from './routes/buyer/tenders/create'
import { Route as BuyerTendersIdRouteImport } from './routes/buyer/tenders/$id'
import { Route as BuyerProposalsIdRouteImport } from './routes/buyer/proposals/$id'
import { Route as AdminTendersPendingRouteImport } from './routes/admin/tenders/pending'
import { Route as AdminTendersIdRouteImport } from './routes/admin/tenders/$id'
import { Route as AdminProposalsProposalIdRouteImport } from './routes/admin/proposals/$proposalId'
import { Route as AdminAccountsPendingRouteImport } from './routes/admin/accounts/pending'
import { Route as AdminAccountsIdRouteImport } from './routes/admin/accounts/$id'
import { Route as SupplierTendersIdIndexRouteImport } from './routes/supplier/tenders/$id.index'
import { Route as SupplierProposalsIdIndexRouteImport } from './routes/supplier/proposals/$id.index'
import { Route as BuyerTendersIdIndexRouteImport } from './routes/buyer/tenders/$id.index'
import { Route as BuyerProposalsIdIndexRouteImport } from './routes/buyer/proposals/$id.index'
import { Route as AdminProposalsProposalIdIndexRouteImport } from './routes/admin/proposals/$proposalId.index'
import { Route as SupplierProposalsIdNegotiationsRouteImport } from './routes/supplier/proposals/$id.negotiations'
import { Route as SupplierProposalsIdEditRouteImport } from './routes/supplier/proposals/$id.edit'
import { Route as BuyerTendersIdProposalsRouteImport } from './routes/buyer/tenders/$id.proposals'
import { Route as BuyerTendersIdEditRouteImport } from './routes/buyer/tenders/$id.edit'
import { Route as BuyerProposalsIdNegotiationsRouteImport } from './routes/buyer/proposals/$id.negotiations'
import { Route as AdminProposalsProposalIdNegotiationsRouteImport } from './routes/admin/proposals/$proposalId.negotiations'
import { Route as SupplierTendersIdProposalsCreateRouteImport } from './routes/supplier/tenders/$id.proposals.create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDashboardRoute = SupplierDashboardRouteImport.update({
  id: '/supplier/dashboard',
  path: '/supplier/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSupplierRoute = RegisterSupplierRouteImport.update({
  id: '/register/supplier',
  path: '/register/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterBuyerRoute = RegisterBuyerRouteImport.update({
  id: '/register/buyer',
  path: '/register/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSuspendedRoute = AccountSuspendedRouteImport.update({
  id: '/account/suspended',
  path: '/account/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRejectedRoute = AccountRejectedRouteImport.update({
  id: '/account/rejected',
  path: '/account/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPendingRoute = AccountPendingRouteImport.update({
  id: '/account/pending',
  path: '/account/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierTendersIndexRoute = SupplierTendersIndexRouteImport.update({
  id: '/supplier/tenders/',
  path: '/supplier/tenders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierProposalsIndexRoute = SupplierProposalsIndexRouteImport.update({
  id: '/supplier/proposals/',
  path: '/supplier/proposals/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerTendersIndexRoute = BuyerTendersIndexRouteImport.update({
  id: '/buyer/tenders/',
  path: '/buyer/tenders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTendersIndexRoute = AdminTendersIndexRouteImport.update({
  id: '/admin/tenders/',
  path: '/admin/tenders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIndexRoute = AdminAccountsIndexRouteImport.update({
  id: '/admin/accounts/',
  path: '/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierTendersIdRoute = SupplierTendersIdRouteImport.update({
  id: '/supplier/tenders/$id',
  path: '/supplier/tenders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierProposalsIdRoute = SupplierProposalsIdRouteImport.update({
  id: '/supplier/proposals/$id',
  path: '/supplier/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerTendersCreateRoute = BuyerTendersCreateRouteImport.update({
  id: '/buyer/tenders/create',
  path: '/buyer/tenders/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerTendersIdRoute = BuyerTendersIdRouteImport.update({
  id: '/buyer/tenders/$id',
  path: '/buyer/tenders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerProposalsIdRoute = BuyerProposalsIdRouteImport.update({
  id: '/buyer/proposals/$id',
  path: '/buyer/proposals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTendersPendingRoute = AdminTendersPendingRouteImport.update({
  id: '/admin/tenders/pending',
  path: '/admin/tenders/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTendersIdRoute = AdminTendersIdRouteImport.update({
  id: '/admin/tenders/$id',
  path: '/admin/tenders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProposalsProposalIdRoute =
  AdminProposalsProposalIdRouteImport.update({
    id: '/admin/proposals/$proposalId',
    path: '/admin/proposals/$proposalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAccountsPendingRoute = AdminAccountsPendingRouteImport.update({
  id: '/admin/accounts/pending',
  path: '/admin/accounts/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsIdRoute = AdminAccountsIdRouteImport.update({
  id: '/admin/accounts/$id',
  path: '/admin/accounts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierTendersIdIndexRoute = SupplierTendersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierTendersIdRoute,
} as any)
const SupplierProposalsIdIndexRoute =
  SupplierProposalsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SupplierProposalsIdRoute,
  } as any)
const BuyerTendersIdIndexRoute = BuyerTendersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerTendersIdRoute,
} as any)
const BuyerProposalsIdIndexRoute = BuyerProposalsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerProposalsIdRoute,
} as any)
const AdminProposalsProposalIdIndexRoute =
  AdminProposalsProposalIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProposalsProposalIdRoute,
  } as any)
const SupplierProposalsIdNegotiationsRoute =
  SupplierProposalsIdNegotiationsRouteImport.update({
    id: '/negotiations',
    path: '/negotiations',
    getParentRoute: () => SupplierProposalsIdRoute,
  } as any)
const SupplierProposalsIdEditRoute = SupplierProposalsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SupplierProposalsIdRoute,
} as any)
const BuyerTendersIdProposalsRoute = BuyerTendersIdProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => BuyerTendersIdRoute,
} as any)
const BuyerTendersIdEditRoute = BuyerTendersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BuyerTendersIdRoute,
} as any)
const BuyerProposalsIdNegotiationsRoute =
  BuyerProposalsIdNegotiationsRouteImport.update({
    id: '/negotiations',
    path: '/negotiations',
    getParentRoute: () => BuyerProposalsIdRoute,
  } as any)
const AdminProposalsProposalIdNegotiationsRoute =
  AdminProposalsProposalIdNegotiationsRouteImport.update({
    id: '/negotiations',
    path: '/negotiations',
    getParentRoute: () => AdminProposalsProposalIdRoute,
  } as any)
const SupplierTendersIdProposalsCreateRoute =
  SupplierTendersIdProposalsCreateRouteImport.update({
    id: '/proposals/create',
    path: '/proposals/create',
    getParentRoute: () => SupplierTendersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account/pending': typeof AccountPendingRoute
  '/account/rejected': typeof AccountRejectedRoute
  '/account/suspended': typeof AccountSuspendedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/register/buyer': typeof RegisterBuyerRoute
  '/register/supplier': typeof RegisterSupplierRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/accounts/pending': typeof AdminAccountsPendingRoute
  '/admin/proposals/$proposalId': typeof AdminProposalsProposalIdRouteWithChildren
  '/admin/tenders/$id': typeof AdminTendersIdRoute
  '/admin/tenders/pending': typeof AdminTendersPendingRoute
  '/buyer/proposals/$id': typeof BuyerProposalsIdRouteWithChildren
  '/buyer/tenders/$id': typeof BuyerTendersIdRouteWithChildren
  '/buyer/tenders/create': typeof BuyerTendersCreateRoute
  '/supplier/proposals/$id': typeof SupplierProposalsIdRouteWithChildren
  '/supplier/tenders/$id': typeof SupplierTendersIdRouteWithChildren
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/tenders/': typeof AdminTendersIndexRoute
  '/buyer/tenders/': typeof BuyerTendersIndexRoute
  '/supplier/proposals/': typeof SupplierProposalsIndexRoute
  '/supplier/tenders/': typeof SupplierTendersIndexRoute
  '/admin/proposals/$proposalId/negotiations': typeof AdminProposalsProposalIdNegotiationsRoute
  '/buyer/proposals/$id/negotiations': typeof BuyerProposalsIdNegotiationsRoute
  '/buyer/tenders/$id/edit': typeof BuyerTendersIdEditRoute
  '/buyer/tenders/$id/proposals': typeof BuyerTendersIdProposalsRoute
  '/supplier/proposals/$id/edit': typeof SupplierProposalsIdEditRoute
  '/supplier/proposals/$id/negotiations': typeof SupplierProposalsIdNegotiationsRoute
  '/admin/proposals/$proposalId/': typeof AdminProposalsProposalIdIndexRoute
  '/buyer/proposals/$id/': typeof BuyerProposalsIdIndexRoute
  '/buyer/tenders/$id/': typeof BuyerTendersIdIndexRoute
  '/supplier/proposals/$id/': typeof SupplierProposalsIdIndexRoute
  '/supplier/tenders/$id/': typeof SupplierTendersIdIndexRoute
  '/supplier/tenders/$id/proposals/create': typeof SupplierTendersIdProposalsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account/pending': typeof AccountPendingRoute
  '/account/rejected': typeof AccountRejectedRoute
  '/account/suspended': typeof AccountSuspendedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/register/buyer': typeof RegisterBuyerRoute
  '/register/supplier': typeof RegisterSupplierRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/accounts/pending': typeof AdminAccountsPendingRoute
  '/admin/tenders/$id': typeof AdminTendersIdRoute
  '/admin/tenders/pending': typeof AdminTendersPendingRoute
  '/buyer/tenders/create': typeof BuyerTendersCreateRoute
  '/admin/accounts': typeof AdminAccountsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/tenders': typeof AdminTendersIndexRoute
  '/buyer/tenders': typeof BuyerTendersIndexRoute
  '/supplier/proposals': typeof SupplierProposalsIndexRoute
  '/supplier/tenders': typeof SupplierTendersIndexRoute
  '/admin/proposals/$proposalId/negotiations': typeof AdminProposalsProposalIdNegotiationsRoute
  '/buyer/proposals/$id/negotiations': typeof BuyerProposalsIdNegotiationsRoute
  '/buyer/tenders/$id/edit': typeof BuyerTendersIdEditRoute
  '/buyer/tenders/$id/proposals': typeof BuyerTendersIdProposalsRoute
  '/supplier/proposals/$id/edit': typeof SupplierProposalsIdEditRoute
  '/supplier/proposals/$id/negotiations': typeof SupplierProposalsIdNegotiationsRoute
  '/admin/proposals/$proposalId': typeof AdminProposalsProposalIdIndexRoute
  '/buyer/proposals/$id': typeof BuyerProposalsIdIndexRoute
  '/buyer/tenders/$id': typeof BuyerTendersIdIndexRoute
  '/supplier/proposals/$id': typeof SupplierProposalsIdIndexRoute
  '/supplier/tenders/$id': typeof SupplierTendersIdIndexRoute
  '/supplier/tenders/$id/proposals/create': typeof SupplierTendersIdProposalsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account/pending': typeof AccountPendingRoute
  '/account/rejected': typeof AccountRejectedRoute
  '/account/suspended': typeof AccountSuspendedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/register/buyer': typeof RegisterBuyerRoute
  '/register/supplier': typeof RegisterSupplierRoute
  '/supplier/dashboard': typeof SupplierDashboardRoute
  '/admin/accounts/$id': typeof AdminAccountsIdRoute
  '/admin/accounts/pending': typeof AdminAccountsPendingRoute
  '/admin/proposals/$proposalId': typeof AdminProposalsProposalIdRouteWithChildren
  '/admin/tenders/$id': typeof AdminTendersIdRoute
  '/admin/tenders/pending': typeof AdminTendersPendingRoute
  '/buyer/proposals/$id': typeof BuyerProposalsIdRouteWithChildren
  '/buyer/tenders/$id': typeof BuyerTendersIdRouteWithChildren
  '/buyer/tenders/create': typeof BuyerTendersCreateRoute
  '/supplier/proposals/$id': typeof SupplierProposalsIdRouteWithChildren
  '/supplier/tenders/$id': typeof SupplierTendersIdRouteWithChildren
  '/admin/accounts/': typeof AdminAccountsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/tenders/': typeof AdminTendersIndexRoute
  '/buyer/tenders/': typeof BuyerTendersIndexRoute
  '/supplier/proposals/': typeof SupplierProposalsIndexRoute
  '/supplier/tenders/': typeof SupplierTendersIndexRoute
  '/admin/proposals/$proposalId/negotiations': typeof AdminProposalsProposalIdNegotiationsRoute
  '/buyer/proposals/$id/negotiations': typeof BuyerProposalsIdNegotiationsRoute
  '/buyer/tenders/$id/edit': typeof BuyerTendersIdEditRoute
  '/buyer/tenders/$id/proposals': typeof BuyerTendersIdProposalsRoute
  '/supplier/proposals/$id/edit': typeof SupplierProposalsIdEditRoute
  '/supplier/proposals/$id/negotiations': typeof SupplierProposalsIdNegotiationsRoute
  '/admin/proposals/$proposalId/': typeof AdminProposalsProposalIdIndexRoute
  '/buyer/proposals/$id/': typeof BuyerProposalsIdIndexRoute
  '/buyer/tenders/$id/': typeof BuyerTendersIdIndexRoute
  '/supplier/proposals/$id/': typeof SupplierProposalsIdIndexRoute
  '/supplier/tenders/$id/': typeof SupplierTendersIdIndexRoute
  '/supplier/tenders/$id/proposals/create': typeof SupplierTendersIdProposalsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account/pending'
    | '/account/rejected'
    | '/account/suspended'
    | '/admin/dashboard'
    | '/buyer/dashboard'
    | '/register/buyer'
    | '/register/supplier'
    | '/supplier/dashboard'
    | '/admin/accounts/$id'
    | '/admin/accounts/pending'
    | '/admin/proposals/$proposalId'
    | '/admin/tenders/$id'
    | '/admin/tenders/pending'
    | '/buyer/proposals/$id'
    | '/buyer/tenders/$id'
    | '/buyer/tenders/create'
    | '/supplier/proposals/$id'
    | '/supplier/tenders/$id'
    | '/admin/accounts/'
    | '/admin/roles/'
    | '/admin/tenders/'
    | '/buyer/tenders/'
    | '/supplier/proposals/'
    | '/supplier/tenders/'
    | '/admin/proposals/$proposalId/negotiations'
    | '/buyer/proposals/$id/negotiations'
    | '/buyer/tenders/$id/edit'
    | '/buyer/tenders/$id/proposals'
    | '/supplier/proposals/$id/edit'
    | '/supplier/proposals/$id/negotiations'
    | '/admin/proposals/$proposalId/'
    | '/buyer/proposals/$id/'
    | '/buyer/tenders/$id/'
    | '/supplier/proposals/$id/'
    | '/supplier/tenders/$id/'
    | '/supplier/tenders/$id/proposals/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account/pending'
    | '/account/rejected'
    | '/account/suspended'
    | '/admin/dashboard'
    | '/buyer/dashboard'
    | '/register/buyer'
    | '/register/supplier'
    | '/supplier/dashboard'
    | '/admin/accounts/$id'
    | '/admin/accounts/pending'
    | '/admin/tenders/$id'
    | '/admin/tenders/pending'
    | '/buyer/tenders/create'
    | '/admin/accounts'
    | '/admin/roles'
    | '/admin/tenders'
    | '/buyer/tenders'
    | '/supplier/proposals'
    | '/supplier/tenders'
    | '/admin/proposals/$proposalId/negotiations'
    | '/buyer/proposals/$id/negotiations'
    | '/buyer/tenders/$id/edit'
    | '/buyer/tenders/$id/proposals'
    | '/supplier/proposals/$id/edit'
    | '/supplier/proposals/$id/negotiations'
    | '/admin/proposals/$proposalId'
    | '/buyer/proposals/$id'
    | '/buyer/tenders/$id'
    | '/supplier/proposals/$id'
    | '/supplier/tenders/$id'
    | '/supplier/tenders/$id/proposals/create'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/account/pending'
    | '/account/rejected'
    | '/account/suspended'
    | '/admin/dashboard'
    | '/buyer/dashboard'
    | '/register/buyer'
    | '/register/supplier'
    | '/supplier/dashboard'
    | '/admin/accounts/$id'
    | '/admin/accounts/pending'
    | '/admin/proposals/$proposalId'
    | '/admin/tenders/$id'
    | '/admin/tenders/pending'
    | '/buyer/proposals/$id'
    | '/buyer/tenders/$id'
    | '/buyer/tenders/create'
    | '/supplier/proposals/$id'
    | '/supplier/tenders/$id'
    | '/admin/accounts/'
    | '/admin/roles/'
    | '/admin/tenders/'
    | '/buyer/tenders/'
    | '/supplier/proposals/'
    | '/supplier/tenders/'
    | '/admin/proposals/$proposalId/negotiations'
    | '/buyer/proposals/$id/negotiations'
    | '/buyer/tenders/$id/edit'
    | '/buyer/tenders/$id/proposals'
    | '/supplier/proposals/$id/edit'
    | '/supplier/proposals/$id/negotiations'
    | '/admin/proposals/$proposalId/'
    | '/buyer/proposals/$id/'
    | '/buyer/tenders/$id/'
    | '/supplier/proposals/$id/'
    | '/supplier/tenders/$id/'
    | '/supplier/tenders/$id/proposals/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AccountPendingRoute: typeof AccountPendingRoute
  AccountRejectedRoute: typeof AccountRejectedRoute
  AccountSuspendedRoute: typeof AccountSuspendedRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  RegisterBuyerRoute: typeof RegisterBuyerRoute
  RegisterSupplierRoute: typeof RegisterSupplierRoute
  SupplierDashboardRoute: typeof SupplierDashboardRoute
  AdminAccountsIdRoute: typeof AdminAccountsIdRoute
  AdminAccountsPendingRoute: typeof AdminAccountsPendingRoute
  AdminProposalsProposalIdRoute: typeof AdminProposalsProposalIdRouteWithChildren
  AdminTendersIdRoute: typeof AdminTendersIdRoute
  AdminTendersPendingRoute: typeof AdminTendersPendingRoute
  BuyerProposalsIdRoute: typeof BuyerProposalsIdRouteWithChildren
  BuyerTendersIdRoute: typeof BuyerTendersIdRouteWithChildren
  BuyerTendersCreateRoute: typeof BuyerTendersCreateRoute
  SupplierProposalsIdRoute: typeof SupplierProposalsIdRouteWithChildren
  SupplierTendersIdRoute: typeof SupplierTendersIdRouteWithChildren
  AdminAccountsIndexRoute: typeof AdminAccountsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminTendersIndexRoute: typeof AdminTendersIndexRoute
  BuyerTendersIndexRoute: typeof BuyerTendersIndexRoute
  SupplierProposalsIndexRoute: typeof SupplierProposalsIndexRoute
  SupplierTendersIndexRoute: typeof SupplierTendersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/dashboard': {
      id: '/supplier/dashboard'
      path: '/supplier/dashboard'
      fullPath: '/supplier/dashboard'
      preLoaderRoute: typeof SupplierDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/supplier': {
      id: '/register/supplier'
      path: '/register/supplier'
      fullPath: '/register/supplier'
      preLoaderRoute: typeof RegisterSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/buyer': {
      id: '/register/buyer'
      path: '/register/buyer'
      fullPath: '/register/buyer'
      preLoaderRoute: typeof RegisterBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/suspended': {
      id: '/account/suspended'
      path: '/account/suspended'
      fullPath: '/account/suspended'
      preLoaderRoute: typeof AccountSuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/rejected': {
      id: '/account/rejected'
      path: '/account/rejected'
      fullPath: '/account/rejected'
      preLoaderRoute: typeof AccountRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/pending': {
      id: '/account/pending'
      path: '/account/pending'
      fullPath: '/account/pending'
      preLoaderRoute: typeof AccountPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/tenders/': {
      id: '/supplier/tenders/'
      path: '/supplier/tenders'
      fullPath: '/supplier/tenders/'
      preLoaderRoute: typeof SupplierTendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/proposals/': {
      id: '/supplier/proposals/'
      path: '/supplier/proposals'
      fullPath: '/supplier/proposals/'
      preLoaderRoute: typeof SupplierProposalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/tenders/': {
      id: '/buyer/tenders/'
      path: '/buyer/tenders'
      fullPath: '/buyer/tenders/'
      preLoaderRoute: typeof BuyerTendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenders/': {
      id: '/admin/tenders/'
      path: '/admin/tenders'
      fullPath: '/admin/tenders/'
      preLoaderRoute: typeof AdminTendersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/': {
      id: '/admin/accounts/'
      path: '/admin/accounts'
      fullPath: '/admin/accounts/'
      preLoaderRoute: typeof AdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/tenders/$id': {
      id: '/supplier/tenders/$id'
      path: '/supplier/tenders/$id'
      fullPath: '/supplier/tenders/$id'
      preLoaderRoute: typeof SupplierTendersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/proposals/$id': {
      id: '/supplier/proposals/$id'
      path: '/supplier/proposals/$id'
      fullPath: '/supplier/proposals/$id'
      preLoaderRoute: typeof SupplierProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/tenders/create': {
      id: '/buyer/tenders/create'
      path: '/buyer/tenders/create'
      fullPath: '/buyer/tenders/create'
      preLoaderRoute: typeof BuyerTendersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/tenders/$id': {
      id: '/buyer/tenders/$id'
      path: '/buyer/tenders/$id'
      fullPath: '/buyer/tenders/$id'
      preLoaderRoute: typeof BuyerTendersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/proposals/$id': {
      id: '/buyer/proposals/$id'
      path: '/buyer/proposals/$id'
      fullPath: '/buyer/proposals/$id'
      preLoaderRoute: typeof BuyerProposalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenders/pending': {
      id: '/admin/tenders/pending'
      path: '/admin/tenders/pending'
      fullPath: '/admin/tenders/pending'
      preLoaderRoute: typeof AdminTendersPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenders/$id': {
      id: '/admin/tenders/$id'
      path: '/admin/tenders/$id'
      fullPath: '/admin/tenders/$id'
      preLoaderRoute: typeof AdminTendersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/proposals/$proposalId': {
      id: '/admin/proposals/$proposalId'
      path: '/admin/proposals/$proposalId'
      fullPath: '/admin/proposals/$proposalId'
      preLoaderRoute: typeof AdminProposalsProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/pending': {
      id: '/admin/accounts/pending'
      path: '/admin/accounts/pending'
      fullPath: '/admin/accounts/pending'
      preLoaderRoute: typeof AdminAccountsPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts/$id': {
      id: '/admin/accounts/$id'
      path: '/admin/accounts/$id'
      fullPath: '/admin/accounts/$id'
      preLoaderRoute: typeof AdminAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/tenders/$id/': {
      id: '/supplier/tenders/$id/'
      path: '/'
      fullPath: '/supplier/tenders/$id/'
      preLoaderRoute: typeof SupplierTendersIdIndexRouteImport
      parentRoute: typeof SupplierTendersIdRoute
    }
    '/supplier/proposals/$id/': {
      id: '/supplier/proposals/$id/'
      path: '/'
      fullPath: '/supplier/proposals/$id/'
      preLoaderRoute: typeof SupplierProposalsIdIndexRouteImport
      parentRoute: typeof SupplierProposalsIdRoute
    }
    '/buyer/tenders/$id/': {
      id: '/buyer/tenders/$id/'
      path: '/'
      fullPath: '/buyer/tenders/$id/'
      preLoaderRoute: typeof BuyerTendersIdIndexRouteImport
      parentRoute: typeof BuyerTendersIdRoute
    }
    '/buyer/proposals/$id/': {
      id: '/buyer/proposals/$id/'
      path: '/'
      fullPath: '/buyer/proposals/$id/'
      preLoaderRoute: typeof BuyerProposalsIdIndexRouteImport
      parentRoute: typeof BuyerProposalsIdRoute
    }
    '/admin/proposals/$proposalId/': {
      id: '/admin/proposals/$proposalId/'
      path: '/'
      fullPath: '/admin/proposals/$proposalId/'
      preLoaderRoute: typeof AdminProposalsProposalIdIndexRouteImport
      parentRoute: typeof AdminProposalsProposalIdRoute
    }
    '/supplier/proposals/$id/negotiations': {
      id: '/supplier/proposals/$id/negotiations'
      path: '/negotiations'
      fullPath: '/supplier/proposals/$id/negotiations'
      preLoaderRoute: typeof SupplierProposalsIdNegotiationsRouteImport
      parentRoute: typeof SupplierProposalsIdRoute
    }
    '/supplier/proposals/$id/edit': {
      id: '/supplier/proposals/$id/edit'
      path: '/edit'
      fullPath: '/supplier/proposals/$id/edit'
      preLoaderRoute: typeof SupplierProposalsIdEditRouteImport
      parentRoute: typeof SupplierProposalsIdRoute
    }
    '/buyer/tenders/$id/proposals': {
      id: '/buyer/tenders/$id/proposals'
      path: '/proposals'
      fullPath: '/buyer/tenders/$id/proposals'
      preLoaderRoute: typeof BuyerTendersIdProposalsRouteImport
      parentRoute: typeof BuyerTendersIdRoute
    }
    '/buyer/tenders/$id/edit': {
      id: '/buyer/tenders/$id/edit'
      path: '/edit'
      fullPath: '/buyer/tenders/$id/edit'
      preLoaderRoute: typeof BuyerTendersIdEditRouteImport
      parentRoute: typeof BuyerTendersIdRoute
    }
    '/buyer/proposals/$id/negotiations': {
      id: '/buyer/proposals/$id/negotiations'
      path: '/negotiations'
      fullPath: '/buyer/proposals/$id/negotiations'
      preLoaderRoute: typeof BuyerProposalsIdNegotiationsRouteImport
      parentRoute: typeof BuyerProposalsIdRoute
    }
    '/admin/proposals/$proposalId/negotiations': {
      id: '/admin/proposals/$proposalId/negotiations'
      path: '/negotiations'
      fullPath: '/admin/proposals/$proposalId/negotiations'
      preLoaderRoute: typeof AdminProposalsProposalIdNegotiationsRouteImport
      parentRoute: typeof AdminProposalsProposalIdRoute
    }
    '/supplier/tenders/$id/proposals/create': {
      id: '/supplier/tenders/$id/proposals/create'
      path: '/proposals/create'
      fullPath: '/supplier/tenders/$id/proposals/create'
      preLoaderRoute: typeof SupplierTendersIdProposalsCreateRouteImport
      parentRoute: typeof SupplierTendersIdRoute
    }
  }
}

interface AdminProposalsProposalIdRouteChildren {
  AdminProposalsProposalIdNegotiationsRoute: typeof AdminProposalsProposalIdNegotiationsRoute
  AdminProposalsProposalIdIndexRoute: typeof AdminProposalsProposalIdIndexRoute
}

const AdminProposalsProposalIdRouteChildren: AdminProposalsProposalIdRouteChildren =
  {
    AdminProposalsProposalIdNegotiationsRoute:
      AdminProposalsProposalIdNegotiationsRoute,
    AdminProposalsProposalIdIndexRoute: AdminProposalsProposalIdIndexRoute,
  }

const AdminProposalsProposalIdRouteWithChildren =
  AdminProposalsProposalIdRoute._addFileChildren(
    AdminProposalsProposalIdRouteChildren,
  )

interface BuyerProposalsIdRouteChildren {
  BuyerProposalsIdNegotiationsRoute: typeof BuyerProposalsIdNegotiationsRoute
  BuyerProposalsIdIndexRoute: typeof BuyerProposalsIdIndexRoute
}

const BuyerProposalsIdRouteChildren: BuyerProposalsIdRouteChildren = {
  BuyerProposalsIdNegotiationsRoute: BuyerProposalsIdNegotiationsRoute,
  BuyerProposalsIdIndexRoute: BuyerProposalsIdIndexRoute,
}

const BuyerProposalsIdRouteWithChildren =
  BuyerProposalsIdRoute._addFileChildren(BuyerProposalsIdRouteChildren)

interface BuyerTendersIdRouteChildren {
  BuyerTendersIdEditRoute: typeof BuyerTendersIdEditRoute
  BuyerTendersIdProposalsRoute: typeof BuyerTendersIdProposalsRoute
  BuyerTendersIdIndexRoute: typeof BuyerTendersIdIndexRoute
}

const BuyerTendersIdRouteChildren: BuyerTendersIdRouteChildren = {
  BuyerTendersIdEditRoute: BuyerTendersIdEditRoute,
  BuyerTendersIdProposalsRoute: BuyerTendersIdProposalsRoute,
  BuyerTendersIdIndexRoute: BuyerTendersIdIndexRoute,
}

const BuyerTendersIdRouteWithChildren = BuyerTendersIdRoute._addFileChildren(
  BuyerTendersIdRouteChildren,
)

interface SupplierProposalsIdRouteChildren {
  SupplierProposalsIdEditRoute: typeof SupplierProposalsIdEditRoute
  SupplierProposalsIdNegotiationsRoute: typeof SupplierProposalsIdNegotiationsRoute
  SupplierProposalsIdIndexRoute: typeof SupplierProposalsIdIndexRoute
}

const SupplierProposalsIdRouteChildren: SupplierProposalsIdRouteChildren = {
  SupplierProposalsIdEditRoute: SupplierProposalsIdEditRoute,
  SupplierProposalsIdNegotiationsRoute: SupplierProposalsIdNegotiationsRoute,
  SupplierProposalsIdIndexRoute: SupplierProposalsIdIndexRoute,
}

const SupplierProposalsIdRouteWithChildren =
  SupplierProposalsIdRoute._addFileChildren(SupplierProposalsIdRouteChildren)

interface SupplierTendersIdRouteChildren {
  SupplierTendersIdIndexRoute: typeof SupplierTendersIdIndexRoute
  SupplierTendersIdProposalsCreateRoute: typeof SupplierTendersIdProposalsCreateRoute
}

const SupplierTendersIdRouteChildren: SupplierTendersIdRouteChildren = {
  SupplierTendersIdIndexRoute: SupplierTendersIdIndexRoute,
  SupplierTendersIdProposalsCreateRoute: SupplierTendersIdProposalsCreateRoute,
}

const SupplierTendersIdRouteWithChildren =
  SupplierTendersIdRoute._addFileChildren(SupplierTendersIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AccountPendingRoute: AccountPendingRoute,
  AccountRejectedRoute: AccountRejectedRoute,
  AccountSuspendedRoute: AccountSuspendedRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  RegisterBuyerRoute: RegisterBuyerRoute,
  RegisterSupplierRoute: RegisterSupplierRoute,
  SupplierDashboardRoute: SupplierDashboardRoute,
  AdminAccountsIdRoute: AdminAccountsIdRoute,
  AdminAccountsPendingRoute: AdminAccountsPendingRoute,
  AdminProposalsProposalIdRoute: AdminProposalsProposalIdRouteWithChildren,
  AdminTendersIdRoute: AdminTendersIdRoute,
  AdminTendersPendingRoute: AdminTendersPendingRoute,
  BuyerProposalsIdRoute: BuyerProposalsIdRouteWithChildren,
  BuyerTendersIdRoute: BuyerTendersIdRouteWithChildren,
  BuyerTendersCreateRoute: BuyerTendersCreateRoute,
  SupplierProposalsIdRoute: SupplierProposalsIdRouteWithChildren,
  SupplierTendersIdRoute: SupplierTendersIdRouteWithChildren,
  AdminAccountsIndexRoute: AdminAccountsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminTendersIndexRoute: AdminTendersIndexRoute,
  BuyerTendersIndexRoute: BuyerTendersIndexRoute,
  SupplierProposalsIndexRoute: SupplierProposalsIndexRoute,
  SupplierTendersIndexRoute: SupplierTendersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
